services:
  frontend:
    image: guitarrapc/agonessample-FrontEnd:v0.9.0
    ports:
      - 5104:80

  server:
    image: guitarrapc/agonessample-BackendServer:v0.9.0
    ports:
      - 5157:5157
    restart: on-failure:1 # emulate new pod when shutdown
