services:
  frontend:
    build:
      dockerfile: ./src/FrontEnd/Dockerfile
      context: .
    image: agonessample-FrontEnd:dev
    ports:
      - 5104:80

  server:
    build:
      dockerfile: ./src/BackendServer/Dockerfile
      context: .
    image: agonessample-BackendServer:dev
    ports:
      - 5157:5157
    restart: on-failure:1 # emulate new pod when shutdown
