services:
  frontend:
    build:
      dockerfile: ./src/SimpleFrontEnd/Dockerfile
      context: .
    image: agonessample-simplefrontend:dev
    ports:
      - 5104:80

  server:
    build:
      dockerfile: ./src/SimpleServer/Dockerfile
      context: .
    image: agonessample-simpleserver:dev
    ports:
      - 5157:80
    restart: on-failure:1 # emulate new pod when shutdown
