services:
  frontend:
    build:
      dockerfile: ./src/FrontendPage/Dockerfile
      context: .
    image: agonessample-frontendpage:dev
    pull_policy: never
    ports:
      - 5104:8080

  server:
    build:
      dockerfile: ./src/BackendServer/Dockerfile
      context: .
    image: agonessample-backendserver:dev
    pull_policy: never
    ports:
      - 5157:5157
    restart: on-failure:1 # emulate new pod when shutdown
