services:
  frontend:
    build:
      dockerfile: ./src/SimpleFrontEnd/Dockerfile
      context: .
    image: agonessample-simplefrontend:dev
    ports:
      - 5104:80

  server:
    build:
      dockerfile: ./src/SimpleBackend/Dockerfile
      context: .
    image: agonessample-simplebackend:dev
    ports:
      - 5157:5157
    restart: on-failure:1 # emulate new pod when shutdown
