apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        kubectl.kubernetes.io/default-container: frontend
    spec:
      serviceAccountName: agones-rest
      containers:
        - name: frontend
          #image: guitarrapc/agonessample:frontendpage-dev
          image: guitarrapc/agonessample:frontendpage-v3.0.2
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      ports:
        - name: default
          portPolicy: Dynamic
          containerPort: 5157
          protocol: TCP
      template:
        metadata:
          labels:
            app: backend
          annotations:
            kubectl.kubernetes.io/default-container: backend
        spec:
          containers:
            - name: backend
              # image: guitarrapc/agonessample:backendserver-dev
              image: guitarrapc/agonessample:backendserver-v3.0.2
              imagePullPolicy: Never
              env:
                - name: ASPNETCORE_ENVIRONMENT
                  value: "Development"
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: backend-autoscaler
  namespace: default
spec:
  fleetName: backend
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 0
      maxReplicas: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-rest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-rest
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - agones.dev
    resources:
      - gameservers
    verbs:
      - list
      - update
      - watch
  - apiGroups:
      - allocation.agones.dev
    resources:
      - gameserverallocations
    verbs:
      - list
      - update
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-rest
  namespace: default
subjects:
  - kind: ServiceAccount
    name: agones-rest
    namespace: default
roleRef:
  kind: ClusterRole
  name: agones-rest
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: default
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 5157
      targetPort: 5157
