apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-frontend
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-frontend
  template:
    metadata:
      labels:
        app: simple-frontend
      annotations:
        kubectl.kubernetes.io/default-container: simple-frontend
    spec:
      serviceAccountName: agones-rest
      containers:
        - name: simple-frontend
          image: guitarrapc/agonessample-simplefrontend:0.7
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: default
              containerPort: 80
              protocol: TCP
---
apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-server
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: simple-server
    spec:
      ports:
        - name: default
          containerPort: 5157
          protocol: TCP
      template:
        metadata:
          labels:
            app: simple-server
          annotations:
            kubectl.kubernetes.io/default-container: simple-server
        spec:
          containers:
            - name: simple-server
              image: guitarrapc/agonessample-simpleserver:0.7
              imagePullPolicy: Always
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              ports:
                - name: api
                  containerPort: 5012
                  protocol: TCP
---
apiVersion: "autoscaling.agones.dev/v1"
kind: FleetAutoscaler
metadata:
  name: simple-server-autoscaler
  namespace: default
spec:
  fleetName: simple-server
  policy:
    type: Buffer
    buffer:
      bufferSize: 2
      minReplicas: 0
      maxReplicas: 10
---
apiVersion: v1
kind: Service
metadata:
  name: simple-frontend
  namespace: default
spec:
  selector:
    app: simple-frontend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agones-rest
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-rest
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - agones.dev
    resources:
      - gameservers
    verbs:
      - list
      - update
      - watch
  - apiGroups:
      - allocation.agones.dev
    resources:
      - gameserverallocations
    verbs:
      - list
      - update
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agones-rest
  namespace: default
subjects:
  - kind: ServiceAccount
    name: agones-rest
    namespace: default
roleRef:
  kind: ClusterRole
  name: agones-rest
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: simple-server
  namespace: default
spec:
  selector:
    app: simple-server
  ports:
    - port: 80
      targetPort: 5012
