name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample v1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create release/nuget."
        required: true
        default: "false"

env:
  OWNER: guitarrapc
  IMAGE_NAME: docker-awscli-kubectl
  DOCKER_BUILDKIT: 1

jobs:
  docker:
    strategy:
      matrix:
        project: ["SimpleBackend", "SimpleFrontEnd"]
        include:
          - project: "SimpleBackend"
            docker-image: guitarrapc/agonessample-simplebackend
          - project: "SimpleFrontEnd"
            docker-image: guitarrapc/agonessample-simplefrontend
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Is tag valid?
        run: if [[ "${{ inputs.tag }}" != "v"* ]]; then exit 1; fi
      - uses: actions/checkout@v2
      # docker build and scan
      - name: Docker Build
        run: |
          docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) -t ${{ matrix.docker-image }}:latest -f src/${{ matrix.project }}/Dockerfile .
          docker tag ${{ matrix.docker-image }}:latest ${{ matrix.docker-image }}:${{ inputs.tag }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ matrix.docker-image }}:latest"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"
      # docker push
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        env:
          DOCKER_USER: ${{ secrets.SYNCED_DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.SYNCED_DOCKER_PASS }}
      - run: docker push ${{ matrix.docker-image }}
        if: ${{ inputs.dry-run  == 'false' }}
      - run: docker push ${{ matrix.docker-image }}:${{ inputs.tag }}
        if: ${{ inputs.dry-run  == 'false' }}

  git:
    needs: [docker]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      # tag
      - run: git tag ${{ inputs.tag }}
        if: ${{ inputs.dry-run  == 'false' }}
      - name: Push changes
        if: ${{ inputs.dry-run  == 'false' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
          branch: ${{ github.ref }}
          tags: true
      # release
      - uses: actions/create-release@v1
        if: ${{ inputs.dry-run  == 'false' }}
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.SYNCED_GITHUB_TOKEN_REPO }}
        with:
          tag_name: ${{ inputs.tag }}
          release_name: ${{ inputs.tag }}
          draft: true
          prerelease: false
