name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "tag: git tag you want create. (sample 1.0.0)"
        required: true
      dry-run:
        description: "dry-run: true will never create release/nuget."
        required: true
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  docker:
    strategy:
      matrix:
        project: ["BackendServer", "FrontendPage"]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: lower
        id: image
        run: |
          echo "latest=guitarrapc/agonessample:${PROJECT,,}-latest" | tee -a "${GITHUB_OUTPUT}"
          echo "current=guitarrapc/agonessample:${PROJECT,,}-v${{ inputs.tag }}" | tee -a "${GITHUB_OUTPUT}"
        env:
          PROJECT: ${{ matrix.project }}
      # docker build and push
      - name: Docker Build
        run: |
          docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) -t "${{ steps.image.outputs.latest }}" -f "src/${{ matrix.project }}/Dockerfile" .
          docker tag "${{ steps.image.outputs.latest }}" "${{ steps.image.outputs.current }}"
      - run: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
        env:
          DOCKER_USER: ${{ secrets.SYNCED_DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.SYNCED_DOCKER_PASS }}
      - run: docker push "${{ steps.image.outputs.latest }}"
        if: ${{ !inputs.dry-run }}
      - run: docker push "${{ steps.image.outputs.current }}"
        if: ${{ !inputs.dry-run }}

  release:
    needs: [docker]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      # tag
      - run: git tag ${{ inputs.tag }}
        if: ${{ !inputs.dry-run }}
      - name: Push changes
        if: ${{ !inputs.dry-run }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
      # release
      - name: Create Release
        run: gh release create ${{ inputs.tag }} --draft --verify-tag --title "Ver.${{ inputs.tag }}" --generate-notes
        if: ${{ !inputs.dry-run }}
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
